#!/bin/bash

#This script assumes that ConnextCMS is installed in the users home directory,
#aliased with the ~ symbol. Edit the directory paths below if this assumption is invalid.

echo Preparing to copy into myCMS directory...

echo Copying Keystone Models
cp keystone/models/*.js ~/myCMS/models/

echo Copying Keystone API Routes
cp keystone/routes/exampleRouter.js ~/myCMS/routes/
cp keystone/routes/api/*.js ~/myCMS/routes/api/
cp keystone/routes/views/*.js ~/myCMS/routes/views/

echo Copying Keystone Views
cp -r keystone/templates/views/*.hbs ~/myCMS/templates/views/